### ISSUE TITLE
Icon for Terraria [Steam]

### ISSUE THREAD

**Issue by Quillan27** [numixproject/numix-core#2524]
Game: Terraria
AppID: 105600
Icon: ![terraria](https://cloud.githubusercontent.com/assets/11085317/9673872/b803d35a-526e-11e5-854d-7c82a9f7c7ef.png)
Notes: This game recently cam out for Linux! Would love an icon. It's an 2D open-world adeventure (and much more)
##

**Comment by mrmeszaros** [comment]
Hello, I just found a stylish icon concept on [deviantart](http://designsnext.deviantart.com/art/Terraria-Icon-Metro-Style-553366778). It could help in the development.

![Terraria Icon Base](http://orig15.deviantart.net/c60f/f/2015/224/6/7/terraria__by_designsnext-d95gkje.png)

Also I do not know if working of a deviantart concept image has any legal issues, so that might be a thing. Also we could ask the creator (if you find the concept nice enough).

Another option would be to crop the tree like in this one:
![Other base concept](http://orig01.deviantart.net/e2b8/f/2011/145/7/e/terraria_icon_by_sakatta-d3h7py9.png)
 Naturally with solid light blue background (sky) and possibly the green and brown parts could be solid too.

**Comment by palob** [comment]
The icon could incorporate something tree-like but both of your designs are much too detailed and fine-grained to be anywhere near Numix.

**Comment by mrmeszaros** [comment]
@palob Yeah, right.
So I made some scaffoldings for this:
![terraria_circle svg](https://cloud.githubusercontent.com/assets/15245298/24064976/185142a2-0b68-11e7-9cdf-593103d06c3c.png)
![terraria_square svg](https://cloud.githubusercontent.com/assets/15245298/24064978/1b2423aa-0b68-11e7-8315-207bc19f93bc.png)

I thought I'd add some soil to look like the icon was a terrarium, and maybe some gleam so that the blue part looked like glass.

What do you think?

**Comment by palob** [comment]
Thanks for your enthusiasm.

The symbol still needs to be streamlined. The trunk should probably just be a vertical line for maximum crispness. For reference, the ``fruho.svg`` design is loosely based on a tree and in ``city.svg`` there are some treetops.


Those squares and circles are actually from our template and denote maximum symbol sizes. Symbols should fit inside the square unless it's a circular shape. So your symbol is slightly too big (unless we make an exception to the rule).

I don't think however square + circle are recognisable as glass. It makes the icon look busy so I'd rather do without.

By the way, we've got some (pretty hidden and incomplete) [design guidelines](https://github.com/numixproject/numix-wiki/wiki/Guidelines).

**Comment by mrmeszaros** [comment]
Hi!
I thougth of something like this:
![image](https://cloud.githubusercontent.com/assets/15245298/24292265/de7c01d2-108c-11e7-910a-403cde668533.png)
I will remake the tree with straight lines to be more crispy.
I kept the guide templates for now, to show that the tree would fit in with this size.
What do you thing about the ground? (grass and dirt, as in a cross-section)

**Comment by palob** [comment]
Yep, that might work.

**Comment by mrmeszaros** [comment]
Just finished an experimental version:
![image](https://cloud.githubusercontent.com/assets/15245298/24379604/03a30cea-1348-11e7-9f07-4304ae4531ab.png)

**Comment by palob** [comment]
That looks sharp :satisfied:

Maybe you can even go up to 28px symbol height.

**Comment by mrmeszaros** [comment]
This is a preview for the 28px symbol:
![image](https://cloud.githubusercontent.com/assets/15245298/24545893/618ebe76-1609-11e7-9031-4b84f28bd0f4.png)
Though it looks better if bigger I have some concerns (related the image):
- The trunk will have to be either 3px wide (and not perfectly grid-aligned **or** not centered)
- or 2px wide and look skinny a bit

Anyways, I'm going to try and make something out of it.

**Comment by mrmeszaros** [comment]
Hi, made a 28px high version (right). In comparison to the smaller 24px high (on the left).
![image](https://cloud.githubusercontent.com/assets/15245298/24589337/d838f16a-17d8-11e7-9f1b-4395401ddcf1.png) ![image](https://cloud.githubusercontent.com/assets/15245298/24589338/dd6b73ec-17d8-11e7-8f5b-60dbd8c3791b.png)

**Comment by palob** [comment]
How does it look at smaller sizes, e.g. 24px, 16px?

**Comment by mrmeszaros** [comment]
@palob here are some rendered pngs:

| Symbol | 16px | 24px | 48px |
|-|:-:|:-:|:-:|
| 24px | ![terraria_circle_24 16](https://cloud.githubusercontent.com/assets/15245298/24775092/c4545dba-1b1b-11e7-949f-c0380d4ac35a.png) | ![terraria_circle_24 24](https://cloud.githubusercontent.com/assets/15245298/24775093/c689a3b0-1b1b-11e7-8065-2c8cc219510d.png) | ![terraria_circle_24 48](https://cloud.githubusercontent.com/assets/15245298/24775317/9531af8c-1b1c-11e7-8bc6-c17fa27d2010.png) |
| 28px | ![terraria_circle_28 16](https://cloud.githubusercontent.com/assets/15245298/24775094/c86e63e6-1b1b-11e7-901d-983a925461d8.png) | ![terraria_circle_28 24](https://cloud.githubusercontent.com/assets/15245298/24775097/c9ebe400-1b1b-11e7-82ed-ab101b703e85.png) | ![terraria_circle_28 48](https://cloud.githubusercontent.com/assets/15245298/24775298/7f145d12-1b1c-11e7-8c16-edb7a563e45f.png) |

With the 28px symbol size, I feel that maybe the trunk could be even twice the width (4px).
 Feel free to comment.
Also, I think of making a PR, so that progress can be tracked - what do you think?

**Comment by palob** [comment]
Feel free to check a 4px trunk and open a PR we'll be happy to merge in the end.
Right now while the 28px symbol looks a bit better at 48px the 24px one scales slightly better down to 16px.

**Comment by mrmeszaros** [comment]
So I made the trunk (and the branches and the grass) wider.
![terraria_circle_28 grid](https://cloud.githubusercontent.com/assets/15245298/24801258/bd510210-1ba3-11e7-85dc-190d7a4fa912.png)
However, as the grid on the image shows the raster of the 16px version, in order to make it nicer, adjustments could be made, which would probably make the 24px version blurrier.
I hope I will be able to make a trade-off between.

**Comment by palob** [comment]
Fixed.
