### ISSUE TITLE
Icons for HipChat

### ISSUE THREAD

**Issue by ediTLJ** [numixproject/numix-core#2561]
Icon=hipchat
Icon=hipchat-attention

Current Numix Circle icons are based on the old HipChat icon.

These are the new HipChat icons:
![hipchat](https://cloud.githubusercontent.com/assets/1533237/10023773/4b6e6cb2-615c-11e5-90b2-cf939abbedfc.png)
![hipchat-attention](https://cloud.githubusercontent.com/assets/1533237/10023784/5d21a79e-615c-11e5-9bd1-1fe9ba427329.png)

Note that these icons are also used as indicators (in system tray).
So something like a blue/orange filled circle with the smile face (without the dialog bubble) would look nicer (it's just my opinion, you guys know better).
##

**Comment by ediTLJ** [comment]
Any hopes of seeing this done?

**Comment by Foggalong** [comment]
It'll be definitely done at some point, but requests take president over enhancements so I'm not sure when it'll happen :)

**Comment by maxtron95** [comment]
I think HipChat is a dead program. It was discontinued in favor of a Slack partnership.

See here: https://www.atlassian.com/partnerships/slack

**Comment by ediTLJ** [comment]
You're probably right, we switched to Slack a long time ago.

**Comment by Foggalong** [comment]
See this is the trick to icon development: if an issue is left open long enough, the software dies and then the issue closes itself :wink:

**Comment by ediTLJ** [comment]
Should I open an issue for the Slack icon too, then? :smile: 
They changed the background a while ago, from purple to white.

**Comment by Foggalong** [comment]
Good question! I can't remember in which issue/PR it was discussed, but we've consciously decided not to bring in the white background when we redesigned it in #4805. It's straying slightly from the OG branding but our reasoning iirc was:

1. Last I checked not all the official Slack apps across mobile/desktop were using white, some of them kept the purple.
2. White is a common baseplate colour in Numix just because so many icons are design such that it's difficult to use anything else (except maybe black). Slack is quite rare in that it works well with the purple baseplate, so it'd 
3. The purple (at least for now) remains innately recognisable as part of Slack's branding because it's used elsewhere in their UI.

So yeah, no update to white from us for now. We might come back to it though in a year or two when the situation will probably have changed (especially 1 & 3). Who knows though, maybe Slack will have a new icon by then :joy:
