### ISSUE TITLE
How to contribute ?

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-core#2647]
I'd like to submit some icons instead of just requesting.

I have Inkscape, but I don't know where to start. Is there a template file somewhere that you have to start with ? Do I just modify an existing icon ?
Is there a list of guidelines to follow ?

Thanks :)
##

**Comment by Foggalong** [comment]
Check out [these guidelines](https://github.com/numixproject/numix-wiki/wiki/Guidelines) for making new icons. Modifying an existing icon is a good way to get started yeah :) if you have any questions feel free to ask!

**Comment by ChuckDaniels87** [comment]
We should really include guidelines in this repo or a link at least in a visible place.

**Comment by MrTimscampi** [comment]
Maybe adding a "Contributing" section to the readme, with a link to the guidelines ?

It's pretty easy once you know the guidelines and you know that you can just edit an existing icon, but if you're not used to contributing to icon themes (It's my first time, I am more on the programming side, usually) it can seem a bit daunting at first :)

**Comment by palob** [comment]
Speaking of the guidelines should I add that it is advisable to merge all shadow elements to a single path or to create the shadow just from the outlining shape instead of duplicating all symbol shapes?

Not only does it save a lot of space but if there are multiple shadow elements on top of each other they add up their opacities in Qt.

@MrTimscampi @ChuckDaniels87 I've seen that in a few of your contributions. You don't need to change anything on existing icons, I'll do another cleanup PR in future:) Just keep it in mind for future PRs.

**Comment by ChuckDaniels87** [comment]
Wopps, I didn't know that (or maybe I read it somewhere and then forgot it
:tongue: ). It would be nice to add it to the guide. I group all objects in
the symbol and then make a shadow, but I'll merge to one path from now on.
