### ISSUE TITLE
Read Only Memories (Steam)

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-core#2653]
Wanting feedback on a proposal for a fullscreen icon for Read Only Memories.

SteamID: 330820

Original icon: 
![unityplayer](https://cloud.githubusercontent.com/assets/1087450/11098555/26d7e56a-88a6-11e5-91be-fb6d4203fbe4.png)

Proposal:
![steam_icon_330820](https://cloud.githubusercontent.com/assets/1087450/11098564/2d7fd602-88a6-11e5-9bd0-50e3d2c89e2f.png)
**SVG:** https://dl.dropboxusercontent.com/u/40932393/steam_icon_330820.svg

Notes: The game is about a sapient AI (the character on both the original icon and my proposal), trans-humanism and other cyberpunk themes. It has a very "early-90s Japanese adventure game" style, similar to games like Policenauts and Snatcher.
Having the icon be the main character's head seemed like a good idea, as he represents the game pretty well, has a round head and bright colors.

Note 2: If necessary, I could remove the symbol at the top of its head, if it doesn't fit in the guideline. It would make the character a bit less recognizable, but it would still work, imho.
##

**Comment by bil-elmoussaoui** [comment]
A really nice one!!

**Comment by Eleuin** [comment]
the mouth part is gonna be a little hard to see at lower resolutions (<= 48px). maybe a little thicker?

**Comment by MrTimscampi** [comment]
Good call, didn't think about that.

Made the mouth more like the original icon, as it was much bigger. (I originally used an in-game screenshot as a base for his expression)
I also changed the white parts to a more off-white color, as suggested in the guidelines (eeeeeeff instead of ffffffff)

![steam_icon_330820](https://cloud.githubusercontent.com/assets/1087450/11127892/da822ca8-8976-11e5-91d9-72c9a982f754.png)
**SVG:** https://dl.dropboxusercontent.com/u/40932393/steam_icon_330820.svg

**Comment by palob** [comment]
How does it look with shadows for all the symbol elements?

**Comment by MrTimscampi** [comment]
Here's with a shadow for the symbol and the teeth's shadow made a bit less harsh:
![steam_icon_330820-shadow](https://cloud.githubusercontent.com/assets/1087450/11163969/a4b7abf2-8ae3-11e5-8bb8-ddeeefda9d99.png)
**SVG:** https://dl.dropboxusercontent.com/u/40932393/steam_icon_330820-shadow.svg

*Note: The game doesn't ship with a .desktop file. I contacted the support person about that, who thanked me for reporting a Linux-specific bug and providing a solution (I essentially sent them a .desktop file for the game), as they don't use Linux internally.
He passed my mail over to the team and they will try to add the .desktop file into the next update. Provided they use the file I sent them, this icon's name will be correct, otherwise I'll send a pull request to hardcode-fixer when the update comes out.*

**Comment by palob** [comment]
I think it's better with shadow and lighter teeth :+1:

**Comment by Foggalong** [comment]
Yeah, that's much better :)

**Comment by MrTimscampi** [comment]
I'll wait until the game's update before making a pull request for this, but given the comments, that should be the last revision of the design pre-pull request :)

**Comment by Foggalong** [comment]
We can do steam icons without the games approval using the hardcode fixer :)

**Comment by palob** [comment]
@MrTimscampi You haven't opened a PR so far.

**Comment by palob** [comment]
@MrTimscampi Do you have this draft still somewhere around?
