### ISSUE TITLE
Icon for Alien: Isolation

### ISSUE THREAD

**Issue by Eleuin** [numixproject/numix-core#2658]
survival sci-fi horror game recently released for linux. based off the old movies

icon=steam_icon_214490
![icon](https://cloud.githubusercontent.com/assets/5553828/11127173/e63a09a2-8940-11e5-9622-96430aa9f555.png)
##

**Comment by MrTimscampi** [comment]
I think I have some ideas for this one.

Either the alien's head from a side view, much like this:
![sya7bsqi](https://cloud.githubusercontent.com/assets/1087450/11127524/0674d9e8-8975-11e5-8638-5fb19be0ad5a.jpeg)

Or the inside of the alien's mouth, kind of like this:
![maxresdefault](https://cloud.githubusercontent.com/assets/1087450/11127538/13ddc11c-8975-11e5-95e5-93a301032808.jpg)

Or, perhaps, the kind of radar/locator that is used through the game (On the left of the screen. The best would be its interface as a symbol, I think):
![alien_isolation1111111111](https://cloud.githubusercontent.com/assets/1087450/11127586/4eda335e-8975-11e5-9b0d-be98c97cfa6e.jpg)

**Comment by wa4557** [comment]
This game is available for linux? Awesome

**Comment by MrTimscampi** [comment]
Here's my proposal:
![steam_icon_214490](https://cloud.githubusercontent.com/assets/1087450/11128418/e5cf2a68-8979-11e5-912c-75c2a291e1ce.png)
**SVG:** https://dl.dropboxusercontent.com/u/40932393/steam_icon_214490.svg

There's a problem in the shadow, though, but I don't know how to fix that without tracing the dots instead of using line styles. (Which I will do if this one is okay with you guys)

**Comment by ChuckDaniels87** [comment]
Nice and really clever design but do not use strokes, you should [convert them into paths](https://github.com/numixproject/numix-wiki/wiki/Guidelines#symbols).

**Comment by MrTimscampi** [comment]
The strokes were mostly to make a quick draft to show here. If people are okay with this one, I'll correct the icon and make it with only paths :)

**Comment by ChuckDaniels87** [comment]
I think it is a really cool icon. :+1:

**Comment by Eleuin** [comment]
@MrTimscampi this design is actually pretty great, just needs some work to be brought up to spec. As for the dots, stroke -> path should fix that
@wa4557 yes, it was recently ported. Also of note, its 50% off on steam until Nov 16, 2015

**Comment by palob** [comment]
@MrTimscampi The icon has some fine details though. Are they halway recognisable at smaller (<48px) sizes?

It looks a bit off-centre. Maybe 1px down?

**Comment by Foggalong** [comment]
I like the designed - if you submit a pull request we can review it :)

**Comment by Eleuin** [comment]
@palob yeah, i like the design, but the details are rather fine. i just rechecked this and its just barely tolerably recognizable at 48px down to like 32px. maybe something can be done with the fine details?

**Comment by MrTimscampi** [comment]
@palob As @Eleuin said, the symbol is recognizable if you go a bit smaller, but it quickly becomes blurry.
I'm thinking about ditching the dotted lines and replacing them with a lighter green, maybe with an alpha. It should make it a bit clearer overall.

Will try to tackle it soon-ish (Had a few designs from my pull requests to correct and I'm working on the icons for Book of Unwritten Tales at the moment, since the issue is much older and they're already almost done).
