### ISSUE TITLE
Icon for DavMail

### ISSUE THREAD

**Issue by scottwillmoore** [numixproject/numix-core#2783]
An icon for the DavMail exchange gateway server is missing.

The desktop file shows the icon is, `Icon=/usr/share/davmail/davmail.png`.

![davmail](https://cloud.githubusercontent.com/assets/9512557/12220075/e305a188-b7b2-11e5-8bf5-73f455820973.png)

Thanks

**Comment by bil-elmoussaoui** [comment]
The icon is hardcoded, can you give us the desktop file name too? :+1:

**Comment by scottwillmoore** [comment]
As in `davmail.desktop`?

**Comment by Necklaces** [comment]
+1

**Comment by Foggalong** [comment]
Please use GitHub reactions for +1s. They just clog up the issue tracker. I'll be removing the comment and yours in a few hours.

**Comment by szekeres2016** [comment]
I also would love to see an icon for this, great application. Since the icon linked appeares to be a generic one (I have seen other project using the exact same icon) it might worth considering making a different one. Since DavMail is a Microsoft Exchange connector application the Exchange project icon could serve as a base like the one on this image:
![image](https://cloud.githubusercontent.com/assets/20751590/17725603/f951d226-644c-11e6-8a35-6221bb767cd0.png)

**Comment by maxtron95** [comment]
@palob Since the davmail icon is merged, This could be closed.
