### ISSUE TITLE
Icon for GitKraken

### ISSUE THREAD

**Issue by ngc7293** [numixproject/numix-core#2880]
An icon is missing for GitKraken.
The current desktop file says 'icon=app', so I assume it's hardcoded.

Thanks

Current icon:
![out](https://cloud.githubusercontent.com/assets/5073717/13556125/0bbbef7e-e3a0-11e5-85b7-fe8c2bf94dc5.png)

The logo from their [website](http://www.gitkraken.com/) for better reference:
![gitkraken](https://cloud.githubusercontent.com/assets/5073717/13556129/17a1077a-e3a0-11e5-871f-e672480a0124.png)

**Comment by Foggalong** [comment]
That's not hardcoded, but is impossible to cover because the name is so non-specific. Please file an issue with the upsteam developer.

**Comment by bil-elmoussaoui** [comment]
+1
The icon name on Arch is `Icon=gitkraken.png`. I think we can use `gitkraken` as an icon name

**Comment by jfexart** [comment]
+1

**Comment by perfecto25** [comment]
I have same issue, running gitcraken on linux mint 17, active gitkr session doesnt show icon,

![gitkrak](https://cloud.githubusercontent.com/assets/10224886/15047667/e76e0f38-12b3-11e6-8fc5-7ae221f9b7ae.jpg)

gitkr v 1.2.0

**Comment by tangb** [comment]
Same problem on xfce running on debian stable, i have no icon on "window buttons" panel item while the icon is ok on app launcher.
Thank you ;)
![gitkraken_icon](https://cloud.githubusercontent.com/assets/2676511/16489040/e21ddd64-3ed3-11e6-96de-9a3e649d0f5f.png)

**Comment by Foggalong** [comment]
As per #3379 icon line to go with is `gitkraken`

**Comment by RyanBeckett** [comment]
![screenshot from 2016-11-13 23-22-27](https://cloud.githubusercontent.com/assets/4528659/20249759/26030326-a9f8-11e6-98f0-2fab62b882c1.png)

Also seeing this issue

**Comment by bil-elmoussaoui** [comment]
The issue is due to a missing StartupWMClass. The WMClass should be defined in the application and in the desktop file. It seems to be missing from both sides. You can check that using `xprop wmclass`  and then click on a GitKraken window, you will see this result "wmclass:  no such atom on any window." which means that the WMClass is missing. 
You can try adding this to then end of your desktop file `StartupWMClass=gitkraken`. This might work, or not. If it does not work you should report that upstream as this can not be fixed from Numix part. As it's definitely a GitKraken issue to fix.

**Comment by bil-elmoussaoui** [comment]
Edit, i guess runing this script will fix your issue https://github.com/bil-elmoussaoui/StartupWMClassFixer

**Comment by RyanBeckett** [comment]
Prefect thanks! Not too sure why it fixed Telegram twice - possibly two *.desktop files?

Output:
Fixed : Atom
Fixed : f.lux
Fixed : GitKraken
Fixed : Google Chrome (stable)
Fixed : Minecraft
Fixed : Telegram
Fixed : Telegram

**Comment by tangb** [comment]
Hi
Thank you for your fix but it doesn't work for me :(
It just fixed Terminator and f.lux, but not gitkraken:
root> ./fix --apply
Fixed : f.lux
Fixed : Terminator
I'm running debian stable version.

**Comment by bil-elmoussaoui** [comment]
@perfecto25 It must be that =)
@tangb Please open an issue upstream in order to keep Numix issues clean :+1:

**Comment by walker-dev** [comment]
for gnome the icon works fine why not put it into the numix ring

https://gist.github.com/boosterdev/fa6133c36b3570df96719233e007f65a#file-gitkraken-svg

**Comment by perfecto25** [comment]
missing icon on centos 7, XFCE

![gitkraken](https://cloud.githubusercontent.com/assets/10224886/25281903/dcc9e420-267c-11e7-99b3-98e402a5826b.png)

**Comment by bil-elmoussaoui** [comment]
@perfecto25 We don't have that icon yet.

**Comment by nsuthar20** [comment]
1. Copy/Paste GitKraken Icon to GitKraken install location:
https://cloud.githubusercontent.com/assets/5073717/13556129/17a1077a-e3a0-11e5-871f-e672480a0124.png

2. Create a Desktop File using below command:
`nano ~/.local/share/applications/gitkraken.desktop
`	 
this will open a blank document.

3. Than add this info into that document, substituting the correct paths for both the **Exec=** and the **Icon=** lines::

> [Desktop Entry]
> Version=1.0
> Type=Application
> Name=GitKrarken
> Exec=/opt/GitKraken/gitkraken
> Icon=/opt/GitKraken/gitkrakenimg.png
> Comment=Development
> Categories=Development;
> Terminal=false
> StartupNotify=true

4. Where **Exec** have GitKraken Application launcher location.
   and **Icon** have Icon location.

5. Done, works fine {OS: Ubuntu 17.04}.

**Comment by palob** [comment]
@nsuthar20 Not sure what you're achieving here but it's a bad practice anyway. 
You should copy the icon to a freedesktop.org compliant location. Either to ``/usr/share/icons/hicolor/<size>/apps`` (if the icon is designed for one of the sizes or you've got multiple sizes) or to ``/usr/share/pixmaps/ and change the icon line inside the ``.desktop`` file to ``Icon=gitkraken``.

Optionally ``~/.local/share/...`` or ``~/.icons/hicolor/...`` instead of ``/usr/share/...``

**Comment by mrmeszaros** [comment]
The icon linked by @boosterdev seems to be ok.

**(1)** I aligned it to fit a 15px circle, however It does not line up well with the 48x48 grid.
**(2)** So I am trying to make the tentacles thinner, but it looks weird.
**(3)** So I thought the kraken could be bigger (it could be lined up much better).

| (1) Not lining up | (2) Weird | (3) Too big |
|:-:|:-:|:-:|
| ![gitkraken circle no line up](https://user-images.githubusercontent.com/15245298/27005421-c268b75e-4e1e-11e7-9cf2-54c5663f40fa.png) | ![gitkraken circle weird](https://user-images.githubusercontent.com/15245298/27005436-f350cd20-4e1e-11e7-8c15-37372a5184ea.png) | ![gitkraken circle big](https://user-images.githubusercontent.com/15245298/27005570-5e25e8e0-4e21-11e7-9008-367b487f759c.png) |

I like option **(3)** the best - what do you think?

**Comment by palob** [comment]
None of them is anywhere close to the Numix guidelines.

The symbol should be 30px wide.

**Comment by bilelmoussaoui** [comment]
Fixed

**Comment by chorsnell** [comment]
Hmm no joy on Xubuntu / XFCE.

Put the png in `/usr/share/pixmaps`

then `~/.local/share/applications/gitkraken.desktop` is...
```
[Desktop Entry]
Name=GitKraken
Comment=Unleash your repo
GenericName=Demo Application
Exec=/usr/share/gitkraken/gitkraken %U
Icon=gitkraken
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Development;Documentation;
MimeType=text/plain;

```

**Comment by palob** [comment]
Are you sure your installation is up to date?

In which place the icon doesn't show up?

**Comment by tangb** [comment]
I still got the same problem, icon is not displayed under on taskbar on fresh install (last week) debian testing under xfce.

**Comment by palob** [comment]
How exactly (from which source) did you install?

**Comment by bilelmoussaoui** [comment]
@tangb We meant how you downloaded the Numix Icon Theme :)

**Comment by tangb** [comment]
😄 Ok
I'm confused but I thought numix was related to Gitkraken project but it seems not.
So I didn't install numix project. So you can ignore all my posts.
Sorry for the inconvenience.

**Comment by uran1980** [comment]
Thanks @poppahorse your solution help me on Kubuntu 18.04 with Gitkraken 5.0.2 installed from snap

**Comment by palob** [comment]
AFAIK snap packages generally have the icons hardcoded. This means you can't get those themed without manal intervention.

**Comment by uran1980** [comment]
Typecaly yes it should, but latest version [gitkraken snap package](https://snapcraft.io/gitkraken) dosn't :(

**Comment by cassianomon** [comment]
Ubuntu 18.04 from snap lost it's icon too

**Comment by palob** [comment]
Yeah, from what I know there's nothing we can do about it. It's a snap issue.
But just to be sure, can you please tell us what the ``Icon=``line inside the respective ``.desktop`` launcher file reads?

**Comment by cassianomon** [comment]
Oh, I didn't found the .desktop file, my `~/.local/share/applications` folder is empty

**Comment by Bodziers** [comment]
palob regarding question about Icon=, in version 136 it was Icon=${SNAP}/usr/share/pixmaps/app.png and in version 137 it is Icon=gitkraken.

**Comment by palob** [comment]
A change for the better!

**Comment by SSvin** [comment]
> palob regarding question about Icon=, in version 136 it was Icon=${SNAP}/usr/share/pixmaps/app.png and in version 137 it is Icon=gitkraken.

How you get this info?

**Comment by Natgho** [comment]
the problem still continues.

**Comment by palob** [comment]
Can you please look up your ``.desktop`` launcher file?

**Comment by Pocketpapa** [comment]
still no icon.

**Comment by Foggalong** [comment]
@Pocketpapa We added [the icon on our end](https://github.com/numixproject/numix-core/blob/master/icons/circle/48/gitkraken.svg) a long time ago, the issue is that the launcher upstream provides is hardcoded. Assuming you're running a version of our theme newer than December 2017  (if you're not, there's you're issue) and the icon still isn't showing it could be an issue where your icon cache just needs updating. To do that either just log out then in again or run `gtk-update-icon-cache`.

**Comment by felipesilvati** [comment]
@dmgauthier It worked here, but I changed to `current`, so that we always get the current version icon:

`Icon=/snap/gitkraken/current/usr/share/pixmaps/gitkraken.png`

I hope it helps!

**Comment by Foggalong** [comment]
I don't usually do this but I'm locking and nuking this thread. The comments people are leaving consistently rehash old ground or else relate to GitKraken itself. In summary:

1. We added an icon for this, `gitkraken.svg`, on our end [a long time ago](https://github.com/numixproject/numix-core/blob/master/icons/circle/48/gitkraken.svg).
2. If you're running the latest version of Numix and GitKraken but the launcher is still not themed then its icon line is likely hardcoded. To fix that you need to find `gitkraken.desktop` and change `Icon=*` to `Icon=gitkraken`. Please file a bug for this upstream with your package maintainer.
3. If you're having an issue which isn't about the launcher being hardcoded, such as a required symlink or update to the design, [file a new issue here](https://github.com/numixproject/numix-core/issues/new).

**Comment by Foggalong** [comment]
I don't usually do this but I'm locking and nuking this thread. The comments people are leaving consistently rehash old ground or else relate to GitKraken itself. In summary:

1. We added an icon for this, `gitkraken.svg`, on our end [a long time ago](https://github.com/numixproject/numix-core/blob/master/icons/circle/48/gitkraken.svg).
2. If you're running the latest version of Numix and GitKraken but the launcher is still not themed then its icon line is likely hardcoded. To fix that you need to find `gitkraken.desktop` and change `Icon=*` to `Icon=gitkraken`. Please file a bug for this upstream with your package maintainer.
3. If your issue is a hardcoded non-launcher icon, such as in a taskbar, then [this will be the fix](https://github.com/bil-elmoussaoui/StartupWMClassFixer).
4. If you're having an issue which isn't about the launcher being hardcoded, such as a required symlink or update to the design, [file a new issue here](https://github.com/numixproject/numix-core/issues/new).
