### ISSUE TITLE
Icon for Dwarf Fortress

### ISSUE THREAD

**Issue by codingHahn** [numixproject/numix-core#3092]
A icon for Dwarf Fortress is mussing in numix-circle.
Game: http://www.bay12games.com/dwarves/
The icon line says "/usr/share/pixmaps/dwarffortress.png". The icon for the arch-linux version is attached.
![dwarffortress](https://cloud.githubusercontent.com/assets/16626332/15182718/498ff620-178e-11e6-9c51-c4df720eca94.png)
Although I think, this fits better:
![4omuqoi](https://cloud.githubusercontent.com/assets/16626332/15182809/a20c459c-178e-11e6-8f62-b22a1686fcfc.png)

EDIT: Made everything right, sorry

**Comment by Foggalong** [comment]
Please add the information set out in the readme

**Comment by edwanvi** [comment]
_a few months later_

Any updates, or has this been backburnered due to more important items?

**Comment by Foggalong** [comment]
For now yeah. We've been getting the build system up and running so that our packaging works properly again. Hopefully the focus will be shifting back to requests now, but [as you can see](https://github.com/numixproject/numix-core/issues?q=is%3Aissue+is%3Aopen+sort%3Acreated-asc) there are issues a lot older than this one waiting to be fixed

**Comment by edwanvi** [comment]
> Jul 31, 2014

I apologize for my ignorance.

**Comment by Foggalong** [comment]
No worries! This issue will get fixed at some point though :)

**Comment by edwanvi** [comment]
[T]/

**Comment by yolonir** [comment]
![dwarffortress](https://user-images.githubusercontent.com/37040281/63343502-be5ed300-c356-11e9-94d1-5be98cd37299.png)
Made an icon as well.

**Comment by palob** [comment]
Could you please submit a pull request?
