### ISSUE TITLE
Four options of Numix icons but only work two

### ISSUE THREAD

**Issue by christianbueno1** [numixproject/numix-core#3514]
Fedora 25, gnome 3.22.1.
I installed that by> dnf copr... etc.
I has changed "$releasever" for "24" in _copr_numix-numix.repo
I have 4 numix options [image](http://i.imgur.com/dYUgD2o.png) only work Numix-Cricle and Numix-Circle-Light but Gnome File icon do not change in both. [images2](http://i.imgur.com/UOEhRx2.png)
That's is normal or I must to fix something?

**Comment by palob** [comment]
It means that the copr repo isn't up to date.
What do you mean by "not working"?

*Numix(-Light)* is just the theme for folder/file/action/status etc. icons, it doesn't come with application icons. When you choose the app icon theme *Numix-Circle(-Light)* you effectively apply both *Numix* + *Numix-Circle*.

**Comment by hlechner** [comment]
@christianbueno1 do you means this icon right?
![image](https://cloud.githubusercontent.com/assets/11244067/21557040/c6324152-ce0d-11e6-905c-f4f494a11cea.png)

Then yes, its normal as palob mentioned.
``Numix`` and ``Numix Light`` are the base of iconset.
The ``Numix-Circle`` and ``Numix-Circle Light`` require the base icons and add the applications icons, that's why you have 4.
