### ISSUE TITLE
Icon Request: Gravit Designer

### ISSUE THREAD

**Issue by AlexisSniffer** [numixproject/numix-core#3702]
| Gravit Designer | appimagekit-gravit-designer | Desktop file name | Original icon |

![screenshot_20170429_131314](https://cloud.githubusercontent.com/assets/9704531/25557773/e3eb25e0-2cdd-11e7-8ce8-f6e620d7be11.png)

Description: Gravit Designer is a full featured free vector design app right at your
Website: https://designer.io

**Comment by palob** [comment]
Hi, we need the ``Icon=`` line from inside the ``desktop`` file.

**Comment by bilelmoussaoui** [comment]
Can you please use the Preview functionality to be sure that the issue output looks as it should be.

**Comment by AlexisSniffer** [comment]
[Desktop Entry]
Name=Gravit Designer
Comment=Gravit Designer is a full featured free vector design app right at your fingertip.
Icon=appimagekit-gravit-designer

**Comment by palob** [comment]
Oh jeeze, looks like all apps installed via AppImage have this nasty ``appimagekit-`` prefix to the icon name.

**Comment by bilelmoussaoui** [comment]
This should be reported appstream then otherwise we wlll have to add a lot of symlinks...

**Comment by maxtron95** [comment]
@palob @Foggalong I reported this and this is the developer's response to the prefix on the Appimage icon name. https://github.com/AppImage/AppImageKit/issues/1026#issuecomment-575884296.

**Comment by Foggalong** [comment]
That's not an especially encouraging response? I guess we add something to hardcode-fixer which just blanket removes any `appimage-*` prefix from desktop files?

**Comment by palob** [comment]
They aren't prepared to further discuss this... The reasoning is odd. Why should have the creator of an appimage have more control over which icon is shown than the user. I do understand the reasoning that the original app creator wants to have control somehow.
Are there appimages which include custom icons?

Regarding the example why would anyone want to install age old Firefox versions? Maybe backrolling 1 or 2 versions in order to isolate regressions, well the Firefox 73 isn't distinguishable from the Firefox 74 one.

"cannot be overridden" - well, it can.

Doing this via hardcode-fixer seems a much less screwy way than prophilactically prefixing ``appimagekit-`` to anything what's present in ``data.json``.

**Comment by maxtron95** [comment]
I know an appimage (https://github.com/icidasset/diffuse) that has an icon name that will conflict with another program. (http://diffuse.sourceforge.net/)

**Comment by Foggalong** [comment]
@creepertron95 That's not an argument for an appimage prefix though, that's an argument for following the `domain.developer.app` naming scheme which is largely standard at this point

**Comment by maxtron95** [comment]
@Foggalong Sadly, the most popular icon themes that I am seeing (Papirus, Suru, Zafiro, Tela, Candy), They all have (at least 1) appimage symlinks at this point (Usually Gravit Designer)

**Comment by palob** [comment]
I think adding ``appimagekit-`` removal to hardcode-fixer or offering a dedicated script is much more reasonable than adding prophylactic symlinks to almost every icon name.
That would however require user interaction.

**Comment by maxtron95** [comment]
The thing is that not every icon has an appimage, Just specific ones that do offer an appimage.

**Comment by palob** [comment]
I would not want to track that.

**Comment by palob** [comment]
upstream defunct / migrated to corel.
