### ISSUE TITLE
Missing annoying Flatpak symlinks

### ISSUE THREAD

**Issue by palob** [numixproject/numix-core#3868]
See those commits by the Papirus guys:

https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/commit/0e2366b0ad6fd8d8f6234ae8648913da5f6812d5

https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/commit/d09f3f85416f1196a097910df1c7d22c1bf7c474

I won't believe there was no way around this. I consider this a Flatpak bug.

**Comment by bilelmoussaoui** [comment]
I don't think it's a Flatpak bug, but it's a bug that exists on Linux since forever and was fixed by Flatpak/Snap packages. they request that for the desktop file and the icon name or whatever things that are specific to the application. If you take just a simple example, VSCode uses code as an icon name, which is used by gedit, scratch and a lot of text editors out there. With flatpak forcing things to be `XXX.XXX.XXXX` this just fix it. As elementary apps will have `io.elementary.code` and VSCode once packaged as flatpak will have `org.microsoft.code` or whatever things they want to use :) 
so it's a  lot of work for now, but it will fix a lot of bugs for us in the future :+1:

**Comment by palob** [comment]
OK, there's actually two collisions I know of: ``lighttable`` and ``timeline`` are both app icons and names of Kdenlive action icons.

However whenever an app changes it's hosting service or its umbrella organisation names adhering to the new naming convention are subject to change again.

**Comment by palob** [comment]
@bil-elmoussaoui Do you know if the icon naming convention is planned to become part of the freedesktop spec? Right now GNOME-related and elementary-related apps aside this is only done downstream (Flathub).

**Comment by bilelmoussaoui** [comment]
@palob I have no idea about that :/
