### ISSUE TITLE
Nautilus icons can not show on Fedora 26

### ISSUE THREAD

**Issue by Skinyi** [numixproject/numix-core#3953]
![2017-10-22 17-59-41](https://user-images.githubusercontent.com/23148648/31860919-238d469a-b755-11e7-8cd0-6840e84df9f2.png)
| Nautilus | file-manager | org.gnome.Nautilus |org.gnome.Nautilus |
| --- | :-- | :-- | :-- |
| `APPLICATION NAME`| `ICON NAME` | `DESKTOP FILE NAME` | ![original](https://cloud.githubusercontent.com/assets/5920259/25233502/e8d0afd4-25d6-11e7-9182-b4102e40ae5a.png) |
![2017-10-22 18-00-26](https://user-images.githubusercontent.com/23148648/31860918-23382656-b755-11e7-89a3-39d463362d4c.png)

Description: `DESCRIPTION OF THE APP`
I downloaded them from the github repo, fedy repo and even fedora official repo, but Nautilus icon both in  Numix Circle Icons and Numix icons does not work.
Website: `LINK TO THE APP`

![2017-10-22 17-59-41](https://user-images.githubusercontent.com/23148648/31860919-238d469a-b755-11e7-8cd0-6840e84df9f2.png)
![Uploading 2017-10-22 17-40-50屏幕截图.png…]()

**Comment by palob** [comment]
This is already [fixed](https://github.com/numixproject/numix-core/blob/39689c7bbb36272c0d72468aaf241fd3994a9005/data.json#L4384).

You're using an outdated package.

Again, please tell how exactly you installed the theme. Otherwise we can't help you.

You can copy&paste the ``.desktop`` file to ``~/.local/share/applications`` and edit it so that the icon line reads ``Icon=nautilus``.
This will fix the Nautilus icon but your installation will still be outdated and lack other new icons.

**Comment by Skinyi** [comment]
This issue had been solved, it was because in `org.gnome.Nautilus.desktop` file, its icon was named org.gnome.Nautilus that in Numix Icons, its name is nautilus, witch didn`t match the required name. I modified the .desktop file and solved the issue, thanks for your help!

**Comment by palob** [comment]
Your installation is still outdated though. You shouldn't need to edit files for non-hardcoded icons.

**Comment by Foggalong** [comment]
People, am I right :man_shrugging:
