### ISSUE TITLE
Spotify has slightly different branding in 2018

### ISSUE THREAD

**Issue by brittyazel** [numixproject/numix-core#4319]
This is a minor issue, but to fit modern Spotify branding standards, I believe the black 'sound waves' inside the current icons should actually be white.

Also the green seems slightly off, it should be:
Green*
#1DB954
R30 G215 B96
C80 M0 Y80 K0

https://beta.developer.spotify.com/branding-guidelines/

**Comment by Foggalong** [comment]
We do change the colours of some branded apps so that they don't stand out too much from the colours used elsewhere in the theme. We'll check over Spotify though to make sure we've not messed with it too much :)

**Comment by brittyazel** [comment]
That's fair. Just wanted to let y'all know.

**Comment by Foggalong** [comment]
Looking through the branding guidelines it looks like we're okay with the black sound waves because that's one of the approved logo options. Here are the rules we are breaking, and the reasons we have for breaking them:

1. The green colour isn't "Spotify green" because we use a gradient for all our baseplates. Both stop greens used however are a close approximation to Spotify green.
2. The sound waves on the icon are smaller than the guidelines as so to fit in with the symbol size of 48px on all the other Numix icons.

Thanks for bringing this to our attention though; we should at some point do a thorough review of the branded icons we have to make sure we're not differing too far from company guidelines without just cause.
