### ISSUE TITLE
Sublime Merge icon

### ISSUE THREAD

**Issue by marsjaninzmarsa** [numixproject/numix-core#4781]
We have lovely icon for Sublime Text, would be nice to provide one for Git companion app from same developers.

**Comment by Foggalong** [comment]
This issue is missing all the details we need to actually fulfil an icon request. Please add the information requested in the README (and issue template) and this will be reopened :relaxed:

**Comment by sundarv85** [comment]
@Foggalong  The video link for requesting the icon in readme is going to a 404 - https://currents.google.com/+NumixprojectOrg/posts/DkRmhFZuWez 

Could you let me know which detail you want in the icon for a normal application.

This issue is for Sublime Merge - https://www.sublimemerge.com/ - for which the icon is not present in numix-core

**Comment by palob** [comment]
Ah, we really should do something about the README, see #4840.

What we need is the line which begins with ``Icon=`` from inside the respective ``.desktop`` launcher file.
You'll find the launcher file in ``/usr/share/applications`` or ``~/.local/share/applications/`` and you need to open it with a text editor in order to find the ``Icon=``line.

The next thing we need is the original app icon. If there's a path after ``Icon=`` that's where you can find it. Otherwise search for what's after ``Icon=`` in ``usr/share/`` (or in you home directory for Flatpak/Snap/appimage apps).
Among others you'll find PNG or SVG files inside a ``icons`` or ``pixmaps`` folder. This is what we need.

Finally, a link to the app's web page/project page/CVS repo/Steam page is useful to get to know what the app is about.
