### ISSUE TITLE
Suggestion: new Telegram logo

### ISSUE THREAD

**Issue by ingria** [numixproject/numix-core#5333]
Telegram refreshed their logo some time ago:

![tg](https://user-images.githubusercontent.com/2178368/83980019-fdc4d300-a91a-11ea-9991-8efa532da1bd.png)

Maybe this icon will look nicer than the old paper plane.

Source:
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256"><g transform="translate(0-796.36)"><circle cx="128" cy="924.36" r="124.12" fill="#2ca5e0" stroke="#fff" stroke-width="7.758"/><path d="m55.54 923.29l83.58-34.438c8.251-3.587 36.23-15.07 36.23-15.07 0 0 12.914-5.02 11.838 7.175-.359 5.02-3.229 22.6-6.098 41.613l-8.968 56.32c0 0-.717 8.251-6.816 9.686-6.098 1.435-16.14-5.02-17.937-6.457-1.435-1.076-26.905-17.219-36.23-25.11-2.511-2.152-5.381-6.457.359-11.479 12.914-11.838 28.34-26.546 37.667-35.873 4.305-4.305 8.61-14.349-9.327-2.152l-50.581 34.08c0 0-5.74 3.587-16.502.359-10.762-3.229-23.318-7.533-23.318-7.533 0 0-8.61-5.381 6.098-11.12" fill="#fff"/></g></svg>
```

**Comment by Foggalong** [comment]
I missed this when the issue was originally posed, not coming across it until reviewing #5460. The pull request confused me because the symbol it was switching to didn't match what my version of Telegram desktop had. I thought it might be just my version being out of date but checking against the latest; that too is using an icon like we currently have in Numix. From there I went down a deep dive of seeing what the wider picture was and the situation is a _mess_.

Telegram has _four_ different versions of its logo all being used in various official places, with inconsistencies across platforms and even between different apps on the same platform.

1. **Paper Plane** is what Numix currently uses and Telegram uses in the [X Android app](https://play.google.com/store/apps/details?id=org.thunderdog.challegram&hl=en) (experimental app), the [Chrome extension](https://play.google.com/store/apps/details?id=org.thunderdog.challegram&hl=en), the [standard desktop app](https://desktop.telegram.org/), their [Facebook page](https://www.facebook.com/Telegram-728628747158725), their [Korean Twitter account](https://twitter.com/telegram_kr), within some user interfaces, and for [tdlib](https://github.com/tdlib).
2. **Simplified Plane** that's requested by this issue (and which @BlueManCZ based their design on) is what Telegram uses [on their homepage](https://telegram.org), the [macOS app](https://macos.telegram.org/), most their [Twitters](twitter.com/telegram), the [standard Android app](https://play.google.com/store/apps/details?id=org.telegram.messenger), the [iOS app](https://apps.apple.com/app/telegram-messenger/id686449807), and slightly modified in [the React app](https://evgeny-nadymov.github.io/telegram-react/).
3. **Navigator** is a distinct design which looks like a GPS arrow, used in their [Windows app](https://www.microsoft.com/en-gb/p/telegram-messenger/9wzdncrdzhs0) and in [the default webapp](web.telegram.org).
4. **Flat Plane** is a flattened version of design 1 which appears in some places exclusively as a favicon and status icon. That said, designs 1, 2, and 3 also appear as favicons or status icons elsewhere in official websites and apps.

This is a table showing all the different appearances mentioned above, really hammering home just what a clusterfuck this is. All these apps are official and current. If it included logos from unofficially developed but officially recommended clients it gets even worse (e.g. the Metro app uses a variant of 2, the Firefox uses a variant of 1, Cutegram uses a variant of 4, etc).

Location | Appearance
:---- | :----
X Android | ![Screenshot from 2020-07-08 15-50-30](https://user-images.githubusercontent.com/5920259/86933738-c708f500-c132-11ea-814c-2aa7d224ce71.png)
Chrome | ![Screenshot from 2020-07-08 15-49-05](https://user-images.githubusercontent.com/5920259/86933665-b0629e00-c132-11ea-8947-b90f23ae82e7.png)
Desktop | ![Screenshot from 2020-07-08 15-38-04](https://user-images.githubusercontent.com/5920259/86933877-f4ee3980-c132-11ea-997b-835ca4983e4e.png)
UI Welcome | ![Screenshot from 2020-07-08 15-53-17](https://user-images.githubusercontent.com/5920259/86934163-48f91e00-c133-11ea-97b4-5d302dafa995.png)
tdlib | ![Screenshot from 2020-07-08 16-08-17](https://user-images.githubusercontent.com/5920259/86935939-4ac3e100-c135-11ea-8409-9557884e416a.png)
Website | ![Screenshot from 2020-07-08 16-01-32](https://user-images.githubusercontent.com/5920259/86935316-97f38300-c134-11ea-88fe-049ba5e8f20c.png)
macOS | ![Screenshot from 2020-07-08 16-04-19](https://user-images.githubusercontent.com/5920259/86935466-c5403100-c134-11ea-8e2c-99cb29fe3f7a.png)
Twitter | ![Screenshot from 2020-07-08 16-09-52](https://user-images.githubusercontent.com/5920259/86936172-8ced2280-c135-11ea-8f26-404da938c70e.png)
Android | ![Screenshot from 2020-07-08 16-14-19](https://user-images.githubusercontent.com/5920259/86936649-36341880-c136-11ea-89ed-a938aa66d430.png)
iOS | ![Screenshot from 2020-07-08 16-14-05](https://user-images.githubusercontent.com/5920259/86936667-3b916300-c136-11ea-96ec-3d90a1a19f0f.png)
React | ![Screenshot from 2020-07-08 16-33-03](https://user-images.githubusercontent.com/5920259/86939140-1baf6e80-c139-11ea-9dee-8d811af8b947.png)
Windows | ![Screenshot from 2020-07-08 16-11-08](https://user-images.githubusercontent.com/5920259/86936326-c3c33880-c135-11ea-84e6-9c976c612403.png)
Webogram | ![Screenshot from 2020-07-08 16-12-41](https://user-images.githubusercontent.com/5920259/86937864-a98a5a00-c137-11ea-9bcb-31bd1c15913c.png)
Favicons | ![Screenshot from 2020-07-08 16-26-48](https://user-images.githubusercontent.com/5920259/86938023-d8083500-c137-11ea-80bb-c5310609ac8d.png)

**Comment by Foggalong** [comment]
What the above information as context, I'm not gonna lie I'm not sure what the case is for switching to the simplified design? It seems wholly worse from a design perspective in that it's bland and less recognisable (yay yet another white symbol on a blue background), but it isn't even the icon of the official applications (desktop and Chrome) being targetted here. I'm happy to listen to the arguments for though since @ingria you went to the trouble of making this issue and @BlueManCZ you want to the trouble of making a new icon.

**Comment by maxtron95** [comment]
I took a look at their official [press kit](https://telegram.org/press) and these are the files that the zip file provided at the `Telegram Logos` section.

![telegram logos](https://user-images.githubusercontent.com/53346722/86946814-8bf5ca00-c110-11ea-8c14-63d133ef03cb.png)

**Comment by BlueManCZ** [comment]
@Foggalong Well done, the nice analysis here. It is a mess, you are right. But it seems to me like they are preparing for replacement in all their apps. I don't know, what takes them so long.

There is another one occurrence of the new logo design, in Telegram account for service notifications.
 
<img src="https://user-images.githubusercontent.com/17854950/86946406-9d5bc800-c14a-11ea-8063-d5e9c3b243f9.png" width=250px>

In defence of the new logo design, I must say, it's better recognisable in small sizes.

![l](https://user-images.githubusercontent.com/17854950/86946827-3db1ec80-c14b-11ea-9c05-3e2d29ef9f76.png) ![2](https://user-images.githubusercontent.com/17854950/86947000-7c47a700-c14b-11ea-8908-293dd752e369.png)

But this is obviously your call @Foggalong and Numix team, when you say you merge it, then you merge it.

**Edit**
There is also [Wikipedia](https://en.wikipedia.org/wiki/Telegram_(software)).

**Comment by ingria** [comment]
I've opened this issue just to make sure you are aware of that alternative design. I personally like the old icon more, but I thought that maybe you'll come up with something good-looking with the new icon.

Also, as far as I know, there's no such thing as "the official Telegram logo" - there are several official logos, and users are allowed to choose whichever they like most:

![index](https://user-images.githubusercontent.com/2178368/86958128-5aa6e980-c164-11ea-967a-c7ce1dcbbb57.jpeg)

**Comment by maxtron95** [comment]
Maybe we can have alternative icons in the Numix Theme and a script to switch icons? (Like Numix Folders)

**Comment by palob** [comment]
But maybe 0.5% of users would bother to use such a script.

**Comment by Foggalong** [comment]
Yeah a script for this alone is a no-go; we have contemplated making a more general script which allows users to switch between alternate icons for a bunch of apps (a la what's possible on Android) before but there are more pressing issues to address before we started sinking developer time into something like that.

Thinking this over, I _am_ going to merge this but keep the current design around in a separate entry. For as long as the Classic design is the design which the Chrome and Desktop apps use  Numix will keep the classic icon as the default, but will switch to the new design when they do.
