### ISSUE TITLE
Re-size external disk/usb icon

### ISSUE THREAD

**Issue by MickAmest** [numixproject/numix-core#5655]
Hello,
I noticed that the icon for external disks/usb looks smaller than the rest of the icons (look at the bottom of the dock). Is this supposed to happen or can it be fixed?.

Thank you! 
![Captura de pantalla de 2020-12-19 22-33-47](https://user-images.githubusercontent.com/59746966/102705232-b95fab80-424a-11eb-8eb4-3d26e7f0c999.png)

**Comment by palob** [comment]
This icon isn't an app icon (it  is a device icon).
We can't change it, otherwise (wrongly scaled) Numix Circle/Square-styled icons will pop up in places they don't belong which looks even worse.

This issue is present with Numix because we use this circle/square baseplate design for app icons which makes them stand out from other icons.

**Comment by MickAmest** [comment]
Ah I see. Got it!! Thanks for explaining.
