### ISSUE TITLE
[Icon Request] Joplin

### ISSUE THREAD

**Issue by saltedcoffii** [numixproject/numix-core#5792]
Please make an icon for [joplin](https://joplinapp.org/) a note taking app. Its .desktop file is called joplin.desktop

**Comment by palob** [comment]
We've already got an icon for joplin. Can you please look up the ``Icon=...`` line in the ``.desktop`` file?

**Comment by saltedcoffii** [comment]
```
$ cat /usr/share/applications/joplin.desktop
[Desktop Entry]
Name=Joplin
Comment=Joplin - a note taking and to-do application with synchronization capabilities for Windows, macOS, Linux, Android and iOS.
Exec=/usr/bin/joplin-desktop
Icon=/usr/share/joplin-desktop/resources/build/icons/128x128.png
Terminal=false
Type=Application
Categories=Application;Office;
```

**Comment by palob** [comment]
This launcher file has the icon path hardcoded which means it can't be themed without further ado.
You can edit the icon line to (or copy the launcher to ``~/.local/share/applications`` and edit it) ``Icon=joplin`` in order to get the Numix icon.

And you can report this to upstream/the packager or you can add the path to this script https://github.com/Foggalong/hardcode-fixer so it can be fixed for other users.

**Comment by saltedcoffii** [comment]
issue filed upstream
