### ISSUE TITLE
Create symbolic link for gnome-online-accounts-gtk

### ISSUE THREAD

**Issue by Initu-Castilhos** [numixproject/numix-core#5858]
Create symbolic link for gnome-online-accounts-gtk .

![Captura de tela de 2024-05-05 00-45-22](https://github.com/numixproject/numix-core/assets/59381215/7e931f19-9048-4904-a0dc-8cfcf0e74d19)
It could be the same cs-online-accounts icon.

**Comment by palob** [comment]
Can you tell me which application this icon is used for?

**Comment by Initu-Castilhos** [comment]
> Você pode me dizer para qual aplicativo esse ícone é usado?

cs-online-accounts

**Comment by ghost** [comment]
Linux Mint have created a GTK Frontend for GNOME Online Accounts (icon name gnome-online-accounts-gtk), now that GNOME's version of this requires libadawaita. It will be in the next Linux Mint (22 due in the summer), and is already in the Arch AUR and Debian Sid repos.

As @Initu-Castilhos says, the hicolor icon is the same as that for cs-online-accounts, so creating a symlink in Numix Circle/Square would be straightforward & consistent (rather than having to create a new icon).
