### ISSUE TITLE
Update the trash icon?

### ISSUE THREAD

**Issue by gitblit** [numixproject/numix-core#680]
I really like this icon theme, but I have to say that the trash icon (at lest as seen in Unity) feels really out of place with the rest of the theme.  Is that a fallback icon (blue-green recycle arrows) or is that part of the theme?

**Comment by HellBringer419** [comment]
I know this issue has been closed long ago, however, if possible, could I just **contribute** icons for the trash can application. I'm talking specifically about the trash icon in Numix **circle** theme (also _not_ the Numix circle _light_ theme). I really want the icon to have a circular look so that it doesn't feel out of place.

Here's a screenshot:
![trash_icon_from_numix_circle_icon_theme](https://user-images.githubusercontent.com/35007817/59560309-a2287800-902d-11e9-94e0-5db19c0acad8.png)

**Comment by palob** [comment]
Thing is, afaik it is not technically an application. Or that is to say the icon name used is that of widely used action/places icon. This is why there isn't a Circle/Square icon and the icon is picked up from the base theme. If we added it we'd have Circle/Square icons pop up in places they don't belong which looks even worse.

**Comment by HellBringer419** [comment]
Well it does seem logical. Okay.
